import { Router } from 'express';
import usersRouter from './users';
import authRouter from './auth';
import studentsRouter from './students';
import teachersRouter from './teachers';
import classesRouter from './classes';
import attendanceRouter from './attendance';
import paymentsRouter from './payments';
import sponsorshipsRouter from './sponsorships';
import reportsRouter from './reports';
import clinicRouter from './clinic';
import timetablesRouter from './timetables';
import messagesRouter from './messages';
import academicRouter from './academic';
import financialRouter from './financial';
import analyticsRouter from './analytics';
import systemRouter from './system';
import filesRouter from './files';
import remindersRouter from './reminders';
// import notificationsRouter from './notifications';
import settingsRouter from './settings';
import resourcesRouter from './resources';
import cfoRouter from './cfo';
import coordinatorRouter from './coordinator';
import staffRouter from './staff';
import staffRolesRouter from './staffRoles';
import currencyRouter from './currency';
import opmRouter from './opm';
// import photosRouter from './photos';

const router = Router();

// API Routes
router.use('/auth', authRouter);
router.use('/users', usersRouter);
router.use('/staff', staffRouter);
router.use('/staff-roles', staffRolesRouter);
router.use('/students', studentsRouter);
router.use('/teachers', teachersRouter);
router.use('/classes', classesRouter);
router.use('/attendance', attendanceRouter);
router.use('/payments', paymentsRouter);
router.use('/sponsorships', sponsorshipsRouter);
router.use('/reports', reportsRouter);
router.use('/clinic', clinicRouter);
router.use('/timetables', timetablesRouter);
router.use('/messages', messagesRouter);
router.use('/academic', academicRouter);
router.use('/financial', financialRouter);
router.use('/analytics', analyticsRouter);
router.use('/system', systemRouter);
router.use('/files', filesRouter);
router.use('/reminders', remindersRouter);
// router.use('/notifications', notificationsRouter);
router.use('/settings', settingsRouter);
router.use('/resources', resourcesRouter);
router.use('/cfo', cfoRouter);
router.use('/coordinator', coordinatorRouter);
router.use('/currency', currencyRouter);
router.use('/opm', opmRouter);
// router.use('/photos', photosRouter);

export default router; 